# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
title: Animesh Garg Home
name: Animesh Garg
email: garg@cs.toronto.edu
description: > # this means to ignore newlines until "url:"
  Assistant Professor of Robotics and Machine Learning
footer_text: #>
  #Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.

url:  # the base hostname & protocol for your site
baseurl:  # the subpath of your site, e.g. /blog/
last_updated: # leave blank if you don't want to display last updated
groupurl: http://www.pair.toronto.edu
# -----------------------------------------------------------------------------
# Open Graph
# -----------------------------------------------------------------------------
# Display links to the page with a preview object on social media.
# To achieve this, change serve_og_meta to true and then provide the URL of the
# preview image as the value of og_image.
serve_og_meta: false # Include Open Graph meta tags in the HTML head
og_image: # The site-wide (default for all links) Open Graph preview image

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: animesh-garg # your GitHub user name
twitter_username: animesh_garg # your Twitter handle
linkedin_username: animeshgarg # your LinkedIn user name
scholar_userid: zp8V7ZMAAAAJ # your Google Scholar ID
orcid_id: # your ORCID ID
medium_username: animesh_garg # your Medium username
quora_username: # your Quora username
publons_id: # your ID on Publons
research_gate_profile: # your profile on ResearchGate
blogger_url: # your blogger URL

# contact_note: Email me at <a href="mailto:%67%61%72%67@%63%73.%74%6F%72%6F%6E%74%6F.%65%64%75">garg@cs.toronto.edu</a>

google_analytics: UA-37485716-1 # out your google-analytics code

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: 
blog_description:  

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname: al-folio # put your disqus shortname

# Optional features
show_social_icons:  true
enable_anchorjs:    false
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 10

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: rouge
highlight_theme: github # https://github.com/jwarby/jekyll-pygments-themes
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Handling Reading
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Includes & excludes
include: ['_pages', ".htaccess"]
exclude: [vendor,"deploy.sh"]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jekyll/scholar
    - jekyll-twitter-plugin
    - jemoji

# -----------------------------------------------------------------------------
# Jekyll-Scholar
# -----------------------------------------------------------------------------
scholar:

  last_name: Garg

  style: apa
  locale: en

  sort_by: year,month,day
  order: descending
  group_by: type
  group_order: ascending
  type_aliases: {inproceedings: article}
  type_names: {unpublished: Preprints,  article: Papers (Journals & Conferences), workshop: Peer-Reviewed Workshops, thesis: Theses, patent: Patents}
  type_order: [article,unpublished,workshop,thesis,patent,misc]


  source: /_bibliography/
  # https://github.com/animesh-garg/animesh-garg.github.io/blob/source/_bibliography/
  bibliography: animesh.bib
  bibliography_template: bib

  # add reversal order in bib page (but not working yet!)
  bibliography_list_attributes:
    reversed: true

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"


# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_google_analytics:  false
enable_mansory:           true
enable_math:              true
enable_tooltips:          false
show_social_icons:        false


# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
# jquery_version: "1.12.4"
# katex_version: "0.9.0"
# anchorjs_version: "3.2.2"


# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------

academicons:
  version: "1.9.0"
  integrity: "sha512-W4yqoT1+8NLkinBLBZko+dFB2ZbHsYLDdr50VElllRcNt2Q4/GSs6u71UHKxB7S6JEMCp5Ve4xjh3eGQl/HRvg=="
bootstrap:
  version: "4.5.2"
  integrity:
    css: "sha512-MoRNloxbStBcD8z3M/2BmnT+rg4IsMxPkXaGh2zD6LGNNFE80W3onsAhRcMAMrSoyWL9xD7Ert0men7vR8LUZg=="
    js: "sha512-M5KW3ztuIICmVIhjSqXe01oV2bpe248gOxqmlcYrEzAvws7Pw3z6BK0iGbrwvdrUQUhi3eXgtxp5I8PDo9YfjQ=="
fontawesome:
  version: "5.14.0"
  integrity: "sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
jquery:
  version: "3.5.1"
  integrity: "sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
mathjax:
  version: "3.1.2"
mansory:
  version: "4.2.2"
  integrity: "sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI="
mdb:
  version: "4.19.1"
  integrity:
    css: "sha512-RO38pBRxYH3SoOprtPTD86JFOclM51/XTIdEPh5j8sj4tp8jmQIx26twG52UaLi//hQldfrh7e51WzP9wuP32Q=="
    js: "sha512-Mug9KHKmroQFMLm93zGrjhibM2z2Obg9l6qFG2qKjXEXkMp/VDkI4uju9m4QKPjWSwQ6O2qzZEnJDEeCw0Blcw=="
popper:
  version: "2.4.4"
  integrity: "sha512-eUQ9hGdLjBjY3F41CScH3UX+4JDSI9zXeroz7hJ+RteoCaY+GP/LDoM8AO+Pt+DRFw3nXqsjh9Zsts8hnYv8/A=="

